name: pettrack
description: Lost & Found App for Pets

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  
  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  intl: ^0.20.2
  
  # Image and Location
  image_picker: ^1.1.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  uuid: ^4.5.1
  # State management
  provider: ^6.0.5
  url_launcher: ^6.1.11
  http: ^1.1.0
  cloudinary_public: ^0.21.0
  # flutter_map: ^8.1.1
  # latlong2: ^0.9.1
  # tflite_flutter: ^0.11.0
  # image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

